### ISSUE TITLE
sync: multi context

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/sync-addons#335]
Sync Studio can be used to integrate two external system. If we already have integration, say odoo-telegram and odoo-github, we may create integration telegram-github. To do it, we need to combine functions from evaluation context of both existing integrations. Currently, it's not possible to do just via UI and we have to create new eval context `_eval_context_telegram_telegram_githtub`, that will just call ``_eval_context_telegram_telegram` and ``_eval_context_telegram_github`.

To resolve this obstacle, we must allow selecting several evaluation contexts for the project. 

1.
`eval_context` field should be replaced wtih `Many2many` field to new model `sync.project.context` (fields `name`, `display_name`, `description`)

Field `sync.project.context::description` is computed in the same way as current `eval_context_description`, i.e. by reading method doc strings

https://github.com/itpp-labs/sync-addons/blob/10532cf3322ab88f108876680950220ea49036f3/sync/models/sync_project.py#L51-L52

https://github.com/itpp-labs/sync-addons/blob/10532cf3322ab88f108876680950220ea49036f3/sync/models/sync_project.py#L92-L98

2.
new version `eval_context_description` is a computed  field, that combines descriptions of selected context records

3. 
The solution must include migration scripts to safely upgrade existing deployments

**Comment by themreza** [comment]
I'm planning to do a prototype.
One thing to consider is the possibility that one evaluation context may unexpectedly override another context's attribute.
Though, it might actually be an inheritance feature if we add a sequence to the evaluation context list. :)
It probably won't happen if developers use unique attributes, or even better, wrap all the attributes in an `AttrDict`. 
But it might be helpful to check for such unwanted cases when choosing evaluation contexts.

**Comment by themreza** [comment]
If we change the field signature of `eval_context` from `Selection` to `Many2many`, then Odoo will immediately throw this error if some modules are still using `eval_context = fields.Selection(selection_add=[...])`.

This particular error is coming from the `sync` module's `sync_project_demo.py`, but at least in our system, we have multiple modules acting as execution contexts.

![image](https://user-images.githubusercontent.com/5465057/161992348-23cb9cfa-d159-4d16-92b9-abda7bad54a4.png)

```
AssertionError: sync.project.eval_context: selection_add=[('odoo2odoo', 'Odoo2odoo'), ('telegram_demo', 'Telegram (Demo)'), ('trello_github', 'Trello & Github')] on non-list selection None
```

Since that's in the code, it's not something that a migration script can fix. I recommend creating a new field called `eval_contexts` that loads `eval_context` values for compatibility and deprecating it over a few versions.

The migration script will just copy existing `eval_context` values into the new `eval_contexts` field.
However, since a module containing `selection_add` can still be installed even after the upgrade, we need a hook on `ir.model.fields.selection`'s `_reflect_selection` to detect new `selection_add` values and create `sync.project.context` records accordingly.

We can announce to developers to stop using `eval_context` and eventually deprecate it.

**Comment by themreza** [comment]
@yelizariev Shall evaluation context methods be defined on the `sync.project.context` model instead as well?
To avoid a breaking change, `_get_eval_context` can look for a match on both `sync.project` (`self`) and `sync.project.context`. If a match is made via `sync.project`, we can log a deprecation notice.

**Comment by themreza** [comment]
Here's my prototype with the migration script.

The following preliminary tests were done on a fresh database, but I'll be testing it in our own local database with existing projects.

Test project:
![image](https://user-images.githubusercontent.com/5465057/162041450-d12c75ac-90b0-4e13-92dd-b635a9a3beba.png)

Test run:
![image](https://user-images.githubusercontent.com/5465057/162040162-50303987-7493-4873-a6e0-d0be9f59d929.png)

In case your decision is to introduce breaking changes, please feel free to modify the code. The current version seems to satisfy our requirements, but I'm still thinking whether execution context methods should be on `sync.project` or `sync.project.context`.

**Comment by themreza** [comment]
Please note that since parameters and secrets are shared among multiple execution contexts, it might be necessary to distinguish them with prefixes.

**Comment by yelizariev** [comment]
@themreza 
Thank you for your contribution. I think to add new API on v15, which I'll port soon. This way we don't break existing deployments/modules with such brave change.
